Kopiert aus Musterlösung für Kompasssuche für Blatt 3

In [19]:
import numpy as np #line:1
def kompasssuche_test (f ,x :np .ndarray ,s0 :float ,theta :float)->int :#line:3	  
    """Kompasssuche algorithm to find the minimum of a function.
    Stops when the expected minimum of 0.0 is reached with a tolerance of 0.001.
    
    Parameters:
        f (callable): the function to minimize.
        x0 (ndarray): the initial point.
        s0 (float): the initial step size.
        theta (float): reduction factor of the step size.
        
    Returns:
        int: number of iterations needed to reach the solution (or max. 1000)
    """
    min =0.0  #Minimum 
    tol =0.001 #tolerance
    D =np .concatenate ((np .identity (len (x )),-np .identity (len (x ))),axis =1 )#D-matrizen kombiniert--> Dimensions Menge
    k =1 # Iterationsschritt
    aktuelle_wert =f(x)#line:23

    while (aktuelle_wert >min +tol ):#line:26
        bolean_count =False #Wie Bedingung für Schleife
        counter_dim =0 #Zähler der Menge der Dvektoren (geht alle Richtungen durch)

        while counter_dim <D .shape [1 ]and not bolean_count :#line:32
            wert_01 =f (x +s0 *D [:,counter_dim ])#neuer Wert für Funktion

            if wert_01 <aktuelle_wert :#Falls Wert besser als ursprünglicher Wert ist , wird neuer Wert übernommen
                x =x +s0 *D [:,counter_dim ] #neuer x wert über Schrittweite s und Einheitsvektor
                aktuelle_wert =wert_01 #Neue wert_01 wird übernommen
                print(aktuelle_wert)  #Ausgabe des Funktionswert in der entsprechenden Iteration
                bolean_count =True #line:43
            counter_dim +=1 #line:44

        if not bolean_count :#
            print('Test')
            s0 =theta *s0 #Anpasssung von s0(step size)
        k +=1 

        if (k >=1000 ):#Abbruch nach 1000 Iterationen
        	break 
    return k 


Fragen / Aufgaben
- Input für x als Array ?
- While Schleife anpassen, sodass andere Abbruchbed.
- bolean_count wie Bedinung für Schleife? Warum ?
- wann kommt in not bolean_count Schleife ?
- s0=theta * s0 , warum ?

In [11]:
def f_a(x):
    return (x+5)**2

In [20]:
kompasssuche_test(f_a,x=np.array([1]),s0=0.5,theta=0.3)

[30.25]
[25.]
[20.25]
[16.]
[12.25]
[9.]
[6.25]
[4.]
[2.25]
[1.]
[0.25]
[0.]


13

In [9]:
import numpy as np

a=(1,2)
print(len(a))
m=np.identity(len(a))
n=-np.identity(len(a))
print(m)
print(n)
kk=np.concatenate((m,n,axis=1)
print(kk)

2
[[1. 0.]
 [0. 1.]]
[[-1. -0.]
 [-0. -1.]]
[[ 1.  0. -1. -0.]
 [ 0.  1. -0. -1.]]
